[package]
name = "bpaf"
version = "0.5.7"
edition = "2021"
categories = ["command-line-interface"]
description = "A simple Command Line Argument Parser with parser combinators"
keywords = ["args", "arguments", "cli", "parser", "parse"]
authors = [ "Michael Baykov <manpacket@gmail.com>" ]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pacak/bpaf"
rust-version = "1.56"
exclude = [".github/workflows"]


[dependencies]
bpaf_derive = { path = "./bpaf_derive", version = "0.2.2", optional = true }

[dev-dependencies]
bpaf = { path = ".",  features = ["derive", "extradocs", "autocomplete"] }


[package.metadata.docs.rs]
features = ["derive", "extradocs", "autocomplete"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]


[features]
derive = ["bpaf_derive"]
extradocs = []
batteries = []
autocomplete = []

[[test]]
name = "completion"
required-features = ["autocomplete"]

[[test]]
name = "derive"
required-features = ["derive"]

[[test]]
name = "batteries"
required-features = ["batteries"]

[[example]]
name = "csample"
required-features = ["autocomplete"]

[workspace]
members = [".", "./bpaf_derive", "./bpaf_cauwugo", "docs"]
