on:
  pull_request:
  push:
    branches:
      - master


name: Check and Lint

jobs:
  windows:
    runs-on: windows-latest
    name: Check windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --all-targets --all-features

  check:
    name: Check linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --all-targets --all-features

      # without autocomplete
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --no-default-features

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --doc --all-features

      # without autocomplete
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --doc --no-default-features

      - name: example documentation
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features -p docs

      - name: should not have any changes
        run: git diff && git diff-index --quiet HEAD --

      - name: Rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps --all-features
        env:
          RUSTDOCFLAGS: '-D warnings'

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output
  compat:
    name: Check compat 1.56
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.56.0
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: -p bpaf

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: -p bpaf_derive
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p bpaf --all-targets --no-default-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p bpaf --all-targets --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p bpaf_derive --all-targets --no-default-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p bpaf_derive --all-targets --all-features
